name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Setup github user
      run: \
        git config --global user.name "Github Actions"
        git config --global user.email 53124886+ArjixWasTaken@users.noreply.github.com

    - uses: borales/actions-yarn@v2.3.0
      with:
          cmd: install # will run `yarn install` command

    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build # will run `yarn build` command
    
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: deploy # will run `yarn deploy` command