name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: borales/actions-yarn@v2.3.0
      with:
          cmd: install # will run `yarn install` command

    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build # will run `yarn build` command
    
    - name: Copy "build" folder out of repo
      run: |
        cp -r build ../mysite-build
    
    - name: whatev
      run: |
        mkdir whatev && cd whatev
        cp -r ../.git .git
        git fetch
        git checkout build
        find -not -path "./.git/*" -not -name ".git" -delete
        cp -r ../build/* .
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply automatic changes
        push_options: --force
        repository: ./whatev
        skip_fetch: false
        branch: build